  server:
    port: 8083
  spring:
    application:
      name: inco-xtgl

  feign:
    hystrix:
      enabled: true

  hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              #feign整合hystrix 光设置Hystrix 超时没用的要配合ribbon超时
              timeoutInMilliseconds: 1000 #该配置需要比ribbon超时时间长
        circuitBreaker:
          #默认20 ，熔断的阈值，如何user服务报错满足3次，熔断器就会打开，就算order之后请求正确的数据也不行。
          requestVolumeThreshold: 1000
          #默认5S ， 等5S之后熔断器会处于半开状态，然后下一次请求的正确和错误讲决定熔断器是否真的关闭和是否继续打开
          sleepWindowInMilliseconds: 8000

    threadpool:
      default:
        coreSize: 60
        maxQueueSize: 200
        queueSizeRejectionThreshold: 200

  ribbon:
    ReadTimeout: 500
    ConnectTimeout: 500
    ExecTimeout: 500
    MaxAutoRetries: 1 #最好设置超时重试

  eureka:
    instance:
      hostname: localhost
      #Eureka Client 发送心跳给 server 端的频率。30s
      lease-renewal-interval-in-seconds: 5

      #    Eureka Server 至上一次收到 client 的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则移除该 Instance。90s
      lease-expiration-duration-in-seconds: 5

      #ip注册
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}



    client:
      # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
      registerWithEureka: true
      # 由于注册中心的职责就是维护服务实例, 并不需要检索服务, 所以也设置为 false
      fetchRegistry: true
      #开启健康检查
      healthcheck:
        enabled: true
      serviceUrl:
        defaultZone: http://xiaoxinmo:xiaoxinmo@localhost:8081/eureka/
